import pandas as pd
import numpy as np
import logging
import os

# ==========================================
# MODULE 10: REGIME-BASED PERFORMANCE ANALYSIS
# ==========================================
# Objective: Quantitatively evaluate whether the NLP sentiment signals 
# perform better in High Volatility (uncertainty) or Low Volatility markets.

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def load_trace() -> pd.DataFrame:
    """Loads the daily strategy trace generated by the Backtester."""
    trace_path = os.path.join(os.getcwd(), 'outputs', 'backtest_trace.csv')
    if not os.path.exists(trace_path):
        logging.error(f"Missing backtest trace at {trace_path}. Run module 7.")
        return None
    df = pd.read_csv(trace_path)
    df['date'] = pd.to_datetime(df['date'])
    return df

def analyze_regimes(df: pd.DataFrame) -> pd.DataFrame:
    """Splits the market into High/Low volatility regimes and computes metrics."""
    # Define Regimes based on median conditional volatility (from GARCH)
    median_vol = df['pred_vol_garch_x'].median()
    df['Regime'] = np.where(df['pred_vol_garch_x'] > median_vol, 'High Volatility', 'Low Volatility')
    
    results = []
    days_in_year = 252
    
    for regime in ['High Volatility', 'Low Volatility']:
        regime_df = df[df['Regime'] == regime]
        
        # 1. Base Predictive Accuracy
        # Did the XGBoost model guess the correct direction of the market?
        correct_direction = np.sign(regime_df['predicted_return_t+1']) == np.sign(regime_df['actual_return_t+1'])
        accuracy = np.mean(correct_direction) * 100
        
        # 2. Strategy Alpha Generation
        # Annualized return scaled for the days spent in this specific regime
        avg_daily_return = regime_df['strategy_return'].mean()
        ann_return = avg_daily_return * days_in_year * 100
        
        # 3. Strategy Hit Ratio (Profitability when exposed)
        active_days = regime_df[regime_df['position'] != 0]
        if len(active_days) > 0:
            hit_ratio = (np.sign(active_days['position']) * active_days['actual_return_t+1'] > 0).mean() * 100
        else:
            hit_ratio = 0
            
        results.append({
            'Regime': regime,
            'Trading_Days': len(regime_df),
            'Directional_Accuracy': accuracy,
            'Hit_Ratio': hit_ratio,
            'Annualized_Return': ann_return
        })
        
    return pd.DataFrame(results)

def main():
    logging.info("Starting Module 10: Market Regime Analysis")
    df = load_trace()
    if df is None: return
    
    regime_df = analyze_regimes(df)
    
    logging.info("==================================================")
    logging.info("          MARKET REGIME PERFORMANCE ANALYSIS        ")
    logging.info("==================================================")
    
    for _, row in regime_df.iterrows():
        logging.info(f"--- {row['Regime']} Regime ---")
        logging.info(f"Days Evaluated      : {row['Trading_Days']}")
        logging.info(f"Predictive Accuracy : {row['Directional_Accuracy']:.2f}%")
        logging.info(f"Trading Hit Ratio   : {row['Hit_Ratio']:.2f}%")
        logging.info(f"Strategy Ann. Return: {row['Annualized_Return']:.2f}%")
        logging.info("--------------------------------------------------")
        
    out_path = os.path.join(os.getcwd(), 'outputs', 'regime_performance.csv')
    regime_df.to_csv(out_path, index=False)
    logging.info(f"Regime performance metrics saved safely to {out_path}")

if __name__ == "__main__":
    main()
