import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import logging
import os

# ==========================================
# MODULE 14: LIVE PERFORMANCE MONITORING
# ==========================================
# Objective: Hardened institutional-grade monitoring system enforcing SSOT.
# Strictly reads upstream executed positions without recalculating logic.
# Implements precise T+1 signal timing, drawdown tracking, and 3-panel dashboards.

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def monitor_live_performance():
    logging.info("Starting Module 14: Live Tracking System (SSOT Enforced)")
    
    pred_path = os.path.join(os.getcwd(), 'outputs', 'daily_prediction.csv')
    market_path = os.path.join(os.getcwd(), 'data', 'csi300_features.csv')
    
    if not os.path.exists(pred_path) or not os.path.exists(market_path):
        logging.error("Missing prediction logs or market data.")
        return
        
    pred_df = pd.read_csv(pred_path)
    market_df = pd.read_csv(market_path)
    
    pred_df['date'] = pd.to_datetime(pred_df['date'])
    market_df['date'] = pd.to_datetime(market_df['date'])
    
    pred_df = pred_df.sort_values('date')
    market_df = market_df.sort_values('date')
    
    # ---------------------------------------------------------
    # 1. SINGLE SOURCE OF TRUTH (SSOT)
    # ---------------------------------------------------------
    # Left merge securely maps prediction from day T onto market day T.
    # No risk parameters are recomputed here. We ingest the pure upstream execution trace.
    if 'execution_uuid' in market_df.columns:
        market_df = market_df.drop(columns=['execution_uuid'])
    df = pd.merge(market_df, pred_df[['date', 'position', 'dir_prob', 'execution_uuid']], on='date', how='left')
    
    # Strict chronological sorting
    df = df.sort_values('date').reset_index(drop=True)
    
    # Forward fill positions for non-trading days (holidays), fill 0 for pre-deployment history
    df['position'] = df['position'].ffill().fillna(0.0)
    df['execution_uuid'] = df['execution_uuid'].ffill().fillna('PRE_DEPLOYMENT_N/A')
    
    # Position validation bounds (Assertion)
    if df['position'].isna().any():
        logging.error("FATAL: NaN values detected in position sizing.")
        return
    assert df['position'].abs().max() <= 1.0001, "FATAL: Leverage exceeded maximum limit of 1.0x"
    
    # ---------------------------------------------------------
    # 2. SIGNAL TIMING (CRITICAL FIX)
    # ---------------------------------------------------------
    # A position calculated at the close of T is held through T+1.
    # Therefore, the strategy return on T+1 is generated by the position from T.
    df['position_shifted'] = df['position'].shift(1).fillna(0.0)
    
    # ---------------------------------------------------------
    # 3. TRANSACTION COST LOGIC
    # ---------------------------------------------------------
    # Turnover occurs strictly when position_t differs from position_{t-1}
    df['turnover'] = df['position_shifted'].diff().abs()
    
    # Force alignment for the very first execution day
    df.loc[df.index[0], 'turnover'] = abs(df.loc[df.index[0], 'position_shifted'])
    df['turnover'] = df['turnover'].fillna(0.0)
    
    # 10 bps strict turnover cost model
    df['t_cost'] = df['turnover'] * 0.001
    
    # ---------------------------------------------------------
    # 4. STRATEGY RETURNS & ALPHA
    # ---------------------------------------------------------
    df['strategy_return'] = (df['position_shifted'] * df['return']) - df['t_cost']
    df['benchmark_return'] = df['return']
    
    # Absolute Alpha calculation
    df['alpha'] = df['strategy_return'] - df['benchmark_return']
    
    # Cumulative returns using proper mathematical compounding (1+R).cumprod()
    df['cum_strategy'] = (1 + df['strategy_return']).cumprod()
    df['cum_benchmark'] = (1 + df['benchmark_return']).cumprod()
    
    # ---------------------------------------------------------
    # 5. INSTITUTIONAL METRICS & DRAWDOWN
    # ---------------------------------------------------------
    # Drawdown (Peak to Trough)
    peak = df['cum_strategy'].cummax()
    peak = peak.replace(0, 1e-6) # Prevent catastrophic zero division
    df['drawdown'] = (df['cum_strategy'] - peak) / peak
    
    # Rolling Sharpe (20-day standard)
    window = min(20, len(df))
    roll_mean = df['strategy_return'].rolling(window, min_periods=2).mean()
    roll_std = df['strategy_return'].rolling(window, min_periods=2).std()
    
    # Secure computation
    df['rolling_sharpe'] = np.where(roll_std > 0, (roll_mean / roll_std) * np.sqrt(252), 0)
    
    # Rolling Accuracy (Directional Prediction T vs Reality T+1)
    df['dir_prob_shifted'] = df['dir_prob'].shift(1)
    df['correct_direction'] = np.sign(df['dir_prob_shifted'] - 0.5) == np.sign(df['return'])
    df['rolling_accuracy'] = df['correct_direction'].rolling(window, min_periods=1).mean() * 100
    
    # ---------------------------------------------------------
    # 5b. MODULE 6: ALPHA DECAY & CALIBRATION COLLAPSE TRACKING
    # ---------------------------------------------------------
    # Rolling Brier Score
    df['is_positive_return'] = (df['return'] > 0).astype(int)
    # Brier Score: (dir_prob_shifted - actual_binary_return)^2
    df['brier_daily'] = (df['dir_prob_shifted'] - df['is_positive_return']) ** 2
    df['rolling_brier'] = df['brier_daily'].rolling(window, min_periods=1).mean()
    
    # Expected Calibration Error (ECE) Proxy
    # Absolute difference between rolling predicted probability and rolling actual hit rate
    df['rolling_pred_prob'] = df['dir_prob_shifted'].rolling(window, min_periods=1).mean()
    df['rolling_ece'] = abs(df['rolling_pred_prob'] - (df['rolling_accuracy'] / 100.0))
    
    # Relative Baseline Degradation
    # Edge vs Passive Benchmark (CSI300)
    roll_bench_mean = df['benchmark_return'].rolling(window, min_periods=2).mean()
    roll_bench_std = df['benchmark_return'].rolling(window, min_periods=2).std()
    df['rolling_bench_sharpe'] = np.where(roll_bench_std > 0, (roll_bench_mean / roll_bench_std) * np.sqrt(252), 0)
    df['relative_edge_vs_bench'] = df['rolling_sharpe'] - df['rolling_bench_sharpe']
    
    # Edge vs Random Classifier
    # A random classifier has ~0 Sharpe before costs, negative after costs.
    # Relative degradation alert trigger
    from config.institutional_config import DEGRADATION_THRESHOLDS, DRIFT_LIMITS
    df['degradation_alert'] = df['rolling_sharpe'] < DEGRADATION_THRESHOLDS["min_acceptable_rolling_sharpe"]
    
    # Additional Rolling Metrics
    downside_returns = df['strategy_return'].copy()
    downside_returns[downside_returns > 0] = 0
    roll_downside_std = downside_returns.rolling(window, min_periods=2).std()
    df['rolling_sortino'] = np.where(roll_downside_std > 0, (roll_mean / roll_downside_std) * np.sqrt(252), 0)
    
    df['rolling_turnover'] = df['turnover'].rolling(window, min_periods=1).mean()
    df['rolling_expectancy'] = df['strategy_return'].rolling(window, min_periods=1).mean()
    
    # ---------------------------------------------------------
    # PHASE 2: LONG-HORIZON STATISTICAL VALIDATION ENGINE
    # ---------------------------------------------------------
    # Active Return & Tracking Error
    df['active_return'] = df['strategy_return'] - df['benchmark_return']
    df['rolling_tracking_error'] = df['active_return'].rolling(window, min_periods=2).std() * np.sqrt(252)
    roll_active_mean = df['active_return'].rolling(window, min_periods=2).mean() * 252
    df['rolling_information_ratio'] = np.where(df['rolling_tracking_error'] > 0, roll_active_mean / df['rolling_tracking_error'], 0)
    
    # Drawdown & Calmar
    roll_max_strat = (1 + df['strategy_return']).cumprod().rolling(window, min_periods=1).max()
    current_cum = (1 + df['strategy_return']).cumprod()
    df['rolling_drawdown'] = (current_cum - roll_max_strat) / roll_max_strat
    df['rolling_max_drawdown'] = df['rolling_drawdown'].rolling(window, min_periods=1).min()
    df['rolling_calmar_ratio'] = np.where(df['rolling_max_drawdown'] < 0, (roll_mean * 252) / abs(df['rolling_max_drawdown']), 0)
    
    # Profit Factor & Win/Loss Ratio
    gross_profit = df['strategy_return'].clip(lower=0).rolling(window, min_periods=1).sum()
    gross_loss = df['strategy_return'].clip(upper=0).abs().rolling(window, min_periods=1).sum()
    df['rolling_profit_factor'] = np.where(gross_loss > 0, gross_profit / gross_loss, 0)
    
    avg_win = df['strategy_return'][df['strategy_return'] > 0].reindex(df.index).rolling(window, min_periods=1).mean()
    avg_loss = df['strategy_return'][df['strategy_return'] < 0].abs().reindex(df.index).rolling(window, min_periods=1).mean()
    df['rolling_win_loss_ratio'] = pd.Series(np.where(avg_loss.fillna(0) > 0, avg_win.fillna(0) / avg_loss.fillna(0), 0)).fillna(0)
    
    # Signal Density & Efficiency
    df['is_invested'] = (df['position'] != 0).astype(int)
    df['rolling_signal_density'] = df['is_invested'].rolling(window, min_periods=1).mean()
    df['rolling_turnover_efficiency'] = np.where(df['rolling_turnover'] > 0, df['rolling_expectancy'] / df['rolling_turnover'], 0)
    
    # Statistical Confidence Intervals (Bootstrap Proxy via Standard Error)
    se_sharpe = np.sqrt(252 / window) # Rough SE for annualized Sharpe
    df['rolling_sharpe_ci_lower'] = df['rolling_sharpe'] - (1.96 * se_sharpe)
    
    p = df['rolling_accuracy'] / 100.0
    se_hit = np.sqrt(p * (1 - p) / window)
    df['rolling_hit_rate_ci_lower'] = (p - 1.96 * se_hit) * 100
    
    # Persistent Degradation Escalation
    df['persistent_degradation_alert'] = df['degradation_alert'].rolling(5).sum() == 5
    
    # Drift Alert
    feature_cols = [c for c in market_df.columns if c not in ['date', 'ticker', 'return', 'volatility', 'volume']]
    if len(feature_cols) > 0:
        df['max_z_score'] = df[feature_cols].abs().max(axis=1)
        df['drift_alert'] = df['max_z_score'] > DRIFT_LIMITS["max_z_score_drift"]
    else:
        df['drift_alert'] = False
        
    df['calibration_alert'] = (df['rolling_brier'] > DEGRADATION_THRESHOLDS["max_acceptable_brier"]) | (df['rolling_ece'] > DEGRADATION_THRESHOLDS["max_acceptable_ece"])
    df['safe_mode_flag'] = (df['position'] == 0.0) & (df['dir_prob'] == 0.5)
    
    # MODULE 6: Rolling Surveillance Manifest Export
    surveillance_cols = [
        'date', 'execution_uuid', 'rolling_sharpe', 'rolling_sortino', 'rolling_brier', 
        'rolling_ece', 'rolling_accuracy', 'rolling_expectancy', 'strategy_return', 
        'benchmark_return', 'relative_edge_vs_bench', 'rolling_turnover', 
        'degradation_alert', 'drift_alert', 'calibration_alert', 'safe_mode_flag',
        'rolling_information_ratio', 'rolling_calmar_ratio', 'rolling_max_drawdown',
        'rolling_profit_factor', 'rolling_win_loss_ratio', 'rolling_signal_density',
        'rolling_turnover_efficiency', 'rolling_sharpe_ci_lower', 'rolling_hit_rate_ci_lower',
        'persistent_degradation_alert'
    ]
    surveillance_df = df[surveillance_cols].copy()
    surveillance_df.rename(columns={'rolling_accuracy': 'rolling_hit_rate', 'strategy_return': 'rolling_strategy_return', 'benchmark_return': 'rolling_benchmark_return'}, inplace=True)
    
    # We append ONLY the latest row (to ensure monotonic timestamps and append-only immutability)
    surv_path = os.path.join(os.getcwd(), 'outputs', 'rolling_surveillance_manifest.csv')
    latest_surv = surveillance_df.iloc[[-1]]
    if not os.path.exists(surv_path):
        latest_surv.to_csv(surv_path, index=False)
    else:
        # Atomic append
        latest_surv.to_csv(surv_path, mode='a', header=False, index=False)
        
    # Hash surveillance manifest
    import hashlib
    with open(surv_path, 'rb') as f:
        surv_hash = hashlib.md5(f.read()).hexdigest()
        
    hash_log_path = os.path.join(os.getcwd(), 'logs', 'surveillance_hash_log.csv')
    os.makedirs(os.path.dirname(hash_log_path), exist_ok=True)
    if not os.path.exists(hash_log_path):
        with open(hash_log_path, 'w') as hl:
            hl.write("timestamp,surveillance_manifest_hash\n")
    with open(hash_log_path, 'a') as hl:
        hl.write(f"{df['date'].iloc[-1]},{surv_hash}\n")
    
    # Align columns for app.py
    df_out = df[['date', 'dir_prob', 'return', 'strategy_return', 'position']].copy()
    df_out.rename(columns={
        'dir_prob': 'prediction',
        'return': 'actual_return',
        'strategy_return': 'pnl',
        'position': 'confidence_raw'
    }, inplace=True)
    df_out['confidence_raw'] = df_out['confidence_raw'] * 100
    
    # Output to disk
    out_csv = os.path.join(os.getcwd(), 'outputs', 'live_tracking.csv')
    df_out.to_csv(out_csv, index=False)
    logging.info(f"Live ledger securely stored and validated at {out_csv}")
    
    # ---------------------------------------------------------
    # 6. DASHBOARD UPGRADE (3-PANEL)
    # ---------------------------------------------------------
    # Smart filtering: Plot only the active trading timeline for visual clarity
    first_trade_idx = df[df['position'] != 0].index.min()
    if pd.isna(first_trade_idx):
        plot_df = df.copy()
    else:
        # Pad the visual with 5 days before the first live execution
        start_idx = max(0, first_trade_idx - 5)
        plot_df = df.iloc[start_idx:].copy()
        
        # Reset visual cumulative base to 1.0 strictly for the plotting frame
        plot_df['cum_strategy'] = (1 + plot_df['strategy_return']).cumprod()
        plot_df['cum_benchmark'] = (1 + plot_df['benchmark_return']).cumprod()
        
        plot_peak = plot_df['cum_strategy'].cummax().replace(0, 1e-6)
        plot_df['drawdown'] = (plot_df['cum_strategy'] - plot_peak) / plot_peak
        
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(14, 12), gridspec_kw={'height_ratios': [2, 1, 1]})
    
    # Panel 1: Cumulative Returns
    ax1.plot(plot_df['date'], plot_df['cum_strategy'], label='News-Driven Strategy (Net)', color='#1f77b4', linewidth=2)
    ax1.plot(plot_df['date'], plot_df['cum_benchmark'], label='CSI 300 Benchmark', color='#7f7f7f', alpha=0.7)
    ax1.set_title('Live Performance: Strategy vs Benchmark', fontsize=14, fontweight='bold')
    ax1.set_ylabel('Cumulative Return')
    ax1.legend(loc='upper left')
    ax1.grid(True, linestyle='--', alpha=0.5)
    
    # Panel 2: Rolling Accuracy
    ax2.plot(plot_df['date'], plot_df['rolling_accuracy'], label=f'{window}-Day Rolling Accuracy', color='#ff7f0e', linewidth=2)
    ax2.axhline(y=50, color='red', linestyle='--', alpha=0.5, label='50% Baseline (Coin Flip)')
    ax2.set_title('Directional Accuracy Edge', fontsize=12, fontweight='bold')
    ax2.set_ylabel('Win Rate (%)')
    ax2.legend(loc='lower left')
    ax2.grid(True, linestyle='--', alpha=0.5)
    
    # Panel 3: Drawdown
    ax3.fill_between(plot_df['date'], plot_df['drawdown'] * 100, 0, color='#d62728', alpha=0.5, label='Underwater Drawdown (Peak-to-Trough)')
    ax3.set_title('Risk Management & Drawdown Depth', fontsize=12, fontweight='bold')
    ax3.set_ylabel('Drawdown (%)')
    ax3.legend(loc='lower left')
    ax3.grid(True, linestyle='--', alpha=0.5)
    
    plt.tight_layout()
    out_png = os.path.join(os.getcwd(), 'outputs', 'live_tracking.png')
    plt.savefig(out_png, dpi=300)
    logging.info(f"3-Panel Institutional Dashboard saved to {out_png}")

if __name__ == "__main__":
    monitor_live_performance()
