import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import logging
import os

# ==========================================
# MODULE 14: LIVE PERFORMANCE MONITORING
# ==========================================
# Objective: Hardened institutional-grade monitoring system enforcing SSOT.
# Strictly reads upstream executed positions without recalculating logic.
# Implements precise T+1 signal timing, drawdown tracking, and 3-panel dashboards.

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def monitor_live_performance():
    logging.info("Starting Module 14: Live Tracking System (SSOT Enforced)")
    
    pred_path = os.path.join(os.getcwd(), 'outputs', 'daily_prediction.csv')
    market_path = os.path.join(os.getcwd(), 'data', 'csi300_features.csv')
    
    if not os.path.exists(pred_path) or not os.path.exists(market_path):
        logging.error("Missing prediction logs or market data.")
        return
        
    pred_df = pd.read_csv(pred_path)
    market_df = pd.read_csv(market_path)
    
    pred_df['date'] = pd.to_datetime(pred_df['date'])
    market_df['date'] = pd.to_datetime(market_df['date'])
    
    pred_df = pred_df.sort_values('date')
    market_df = market_df.sort_values('date')
    
    # ---------------------------------------------------------
    # 1. SINGLE SOURCE OF TRUTH (SSOT)
    # ---------------------------------------------------------
    # Left merge securely maps prediction from day T onto market day T.
    # No risk parameters are recomputed here. We ingest the pure upstream execution trace.
    df = pd.merge(market_df, pred_df[['date', 'position', 'predicted_return']], on='date', how='left')
    
    # Strict chronological sorting
    df = df.sort_values('date').reset_index(drop=True)
    
    # Forward fill positions for non-trading days (holidays), fill 0 for pre-deployment history
    df['position'] = df['position'].ffill().fillna(0.0)
    
    # Position validation bounds (Assertion)
    if df['position'].isna().any():
        logging.error("FATAL: NaN values detected in position sizing.")
        return
    assert df['position'].abs().max() <= 1.0001, "FATAL: Leverage exceeded maximum limit of 1.0x"
    
    # ---------------------------------------------------------
    # 2. SIGNAL TIMING (CRITICAL FIX)
    # ---------------------------------------------------------
    # A position calculated at the close of T is held through T+1.
    # Therefore, the strategy return on T+1 is generated by the position from T.
    df['position_shifted'] = df['position'].shift(1).fillna(0.0)
    
    # ---------------------------------------------------------
    # 3. TRANSACTION COST LOGIC
    # ---------------------------------------------------------
    # Turnover occurs strictly when position_t differs from position_{t-1}
    df['turnover'] = df['position_shifted'].diff().abs()
    
    # Force alignment for the very first execution day
    df.loc[df.index[0], 'turnover'] = abs(df.loc[df.index[0], 'position_shifted'])
    df['turnover'] = df['turnover'].fillna(0.0)
    
    # 10 bps strict turnover cost model
    df['t_cost'] = df['turnover'] * 0.001
    
    # ---------------------------------------------------------
    # 4. STRATEGY RETURNS & ALPHA
    # ---------------------------------------------------------
    df['strategy_return'] = (df['position_shifted'] * df['return']) - df['t_cost']
    df['benchmark_return'] = df['return']
    
    # Absolute Alpha calculation
    df['alpha'] = df['strategy_return'] - df['benchmark_return']
    
    # Cumulative returns
    df['cum_strategy'] = np.exp(df['strategy_return'].cumsum())
    df['cum_benchmark'] = np.exp(df['benchmark_return'].cumsum())
    
    # ---------------------------------------------------------
    # 5. INSTITUTIONAL METRICS & DRAWDOWN
    # ---------------------------------------------------------
    # Drawdown (Peak to Trough)
    peak = df['cum_strategy'].cummax()
    peak = peak.replace(0, 1e-6) # Prevent catastrophic zero division
    df['drawdown'] = (df['cum_strategy'] - peak) / peak
    
    # Rolling Sharpe (20-day standard)
    window = min(20, len(df))
    roll_mean = df['strategy_return'].rolling(window, min_periods=2).mean()
    roll_std = df['strategy_return'].rolling(window, min_periods=2).std()
    
    # Secure computation
    df['rolling_sharpe'] = np.where(roll_std > 0, (roll_mean / roll_std) * np.sqrt(252), 0)
    
    # Rolling Accuracy (Directional Prediction T vs Reality T+1)
    df['predicted_return_shifted'] = df['predicted_return'].shift(1)
    df['correct_direction'] = np.sign(df['predicted_return_shifted']) == np.sign(df['return'])
    df['rolling_accuracy'] = df['correct_direction'].rolling(window, min_periods=1).mean() * 100
    
    # Output to disk
    out_csv = os.path.join(os.getcwd(), 'outputs', 'live_tracking.csv')
    df.to_csv(out_csv, index=False)
    logging.info(f"Live ledger securely stored and validated at {out_csv}")
    
    # ---------------------------------------------------------
    # 6. DASHBOARD UPGRADE (3-PANEL)
    # ---------------------------------------------------------
    # Smart filtering: Plot only the active trading timeline for visual clarity
    first_trade_idx = df[df['position'] != 0].index.min()
    if pd.isna(first_trade_idx):
        plot_df = df.copy()
    else:
        # Pad the visual with 5 days before the first live execution
        start_idx = max(0, first_trade_idx - 5)
        plot_df = df.iloc[start_idx:].copy()
        
        # Reset visual cumulative base to 1.0 strictly for the plotting frame
        plot_df['cum_strategy'] = np.exp(plot_df['strategy_return'].cumsum())
        plot_df['cum_benchmark'] = np.exp(plot_df['benchmark_return'].cumsum())
        
        plot_peak = plot_df['cum_strategy'].cummax().replace(0, 1e-6)
        plot_df['drawdown'] = (plot_df['cum_strategy'] - plot_peak) / plot_peak
        
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(14, 12), gridspec_kw={'height_ratios': [2, 1, 1]})
    
    # Panel 1: Cumulative Returns
    ax1.plot(plot_df['date'], plot_df['cum_strategy'], label='News-Driven Strategy (Net)', color='#1f77b4', linewidth=2)
    ax1.plot(plot_df['date'], plot_df['cum_benchmark'], label='CSI 300 Benchmark', color='#7f7f7f', alpha=0.7)
    ax1.set_title('Live Performance: Strategy vs Benchmark', fontsize=14, fontweight='bold')
    ax1.set_ylabel('Cumulative Return')
    ax1.legend(loc='upper left')
    ax1.grid(True, linestyle='--', alpha=0.5)
    
    # Panel 2: Rolling Accuracy
    ax2.plot(plot_df['date'], plot_df['rolling_accuracy'], label=f'{window}-Day Rolling Accuracy', color='#ff7f0e', linewidth=2)
    ax2.axhline(y=50, color='red', linestyle='--', alpha=0.5, label='50% Baseline (Coin Flip)')
    ax2.set_title('Directional Accuracy Edge', fontsize=12, fontweight='bold')
    ax2.set_ylabel('Win Rate (%)')
    ax2.legend(loc='lower left')
    ax2.grid(True, linestyle='--', alpha=0.5)
    
    # Panel 3: Drawdown
    ax3.fill_between(plot_df['date'], plot_df['drawdown'] * 100, 0, color='#d62728', alpha=0.5, label='Underwater Drawdown (Peak-to-Trough)')
    ax3.set_title('Risk Management & Drawdown Depth', fontsize=12, fontweight='bold')
    ax3.set_ylabel('Drawdown (%)')
    ax3.legend(loc='lower left')
    ax3.grid(True, linestyle='--', alpha=0.5)
    
    plt.tight_layout()
    out_png = os.path.join(os.getcwd(), 'outputs', 'live_tracking.png')
    plt.savefig(out_png, dpi=300)
    logging.info(f"3-Panel Institutional Dashboard saved to {out_png}")

if __name__ == "__main__":
    monitor_live_performance()
