import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import logging
import os

# ==========================================
# MODULE 11: DEEP PERFORMANCE ANALYSIS
# ==========================================
# Objective: Generate institutional-grade performance tear sheets, 
# calculating Rolling Sharpe ratios, Drawdown curves, and identifying 
# periods of underperformance.

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def load_trace() -> pd.DataFrame:
    """Loads the daily strategy trace generated by the Backtester."""
    trace_path = os.path.join(os.getcwd(), 'outputs', 'backtest_trace.csv')
    if not os.path.exists(trace_path):
        logging.error(f"Missing backtest trace at {trace_path}. Run module 7.")
        return None
    df = pd.read_csv(trace_path)
    df['date'] = pd.to_datetime(df['date'])
    return df

def calculate_deep_metrics(df: pd.DataFrame) -> pd.DataFrame:
    """Calculates time-series risk metrics: Rolling Sharpe and Drawdown."""
    days = 252 # Trading days in a year
    
    # 1. Rolling Sharpe Ratio (6-month rolling window = ~126 days)
    window = 126
    df['strat_roll_mean'] = df['strategy_return'].rolling(window=window).mean() * days
    df['strat_roll_vol'] = df['strategy_return'].rolling(window=window).std() * np.sqrt(days)
    
    # Avoid Division by Zero
    df['rolling_sharpe'] = np.where(
        df['strat_roll_vol'] > 0, 
        df['strat_roll_mean'] / df['strat_roll_vol'], 
        0
    )
    
    # 2. Drawdown Curve
    # Strategy Drawdown
    df['strat_peak'] = df['cum_strategy'].cummax()
    df['strat_drawdown'] = (df['cum_strategy'] - df['strat_peak']) / df['strat_peak']
    
    # Benchmark Drawdown
    df['bench_peak'] = df['cum_benchmark'].cummax()
    df['bench_drawdown'] = (df['cum_benchmark'] - df['bench_peak']) / df['bench_peak']
    
    return df

def analyze_periods(df: pd.DataFrame):
    """Aggregates returns to identify the strictly best and worst trading periods."""
    # Group by Year-Month
    df['month_year'] = df['date'].dt.to_period('M')
    
    # Sum log returns for the month
    monthly_ret = df.groupby('month_year')['strategy_return'].sum()
    
    best_month = monthly_ret.idxmax()
    worst_month = monthly_ret.idxmin()
    
    logging.info("==================================================")
    logging.info("        STRATEGY EXTREME PERIOD ANALYSIS          ")
    logging.info("==================================================")
    logging.info(f"Best Period (Monthly)  : {best_month} | Gross Return: {monthly_ret.max()*100:6.2f}%")
    logging.info(f"Worst Period (Monthly) : {worst_month} | Gross Return: {monthly_ret.min()*100:6.2f}%")
    logging.info("==================================================")

def plot_advanced_metrics(df: pd.DataFrame):
    """Generates a professional 2-panel tear sheet (Returns & Drawdown)."""
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10), gridspec_kw={'height_ratios': [2, 1]})
    
    # ---------------------------------------------------------
    # Top Panel: Cumulative Returns
    # ---------------------------------------------------------
    ax1.plot(df['date'], df['cum_strategy'], label='News-Driven Alpha (Risk Managed)', color='#1f77b4', linewidth=2.5)
    ax1.plot(df['date'], df['cum_benchmark'], label='CSI 300 Benchmark', color='#7f7f7f', alpha=0.7, linewidth=1.5)
    
    ax1.set_title('Strategy Absolute Performance vs Benchmark', fontsize=16, fontweight='bold', pad=10)
    ax1.set_ylabel('Cumulative Log Return (Base 1.0)', fontsize=12)
    ax1.legend(loc='upper left', frameon=True, shadow=True)
    ax1.grid(True, linestyle='--', alpha=0.4)
    
    # ---------------------------------------------------------
    # Bottom Panel: Drawdown Curve
    # ---------------------------------------------------------
    # Fill the strategy drawdown with red to visually emphasize risk
    ax2.fill_between(df['date'], df['strat_drawdown'], 0, color='#d62728', alpha=0.3, label='Strategy Drawdown Depth')
    
    # Overlay the benchmark drawdown as a line for context
    ax2.plot(df['date'], df['bench_drawdown'], color='#7f7f7f', alpha=0.8, linewidth=1.5, label='Benchmark Drawdown')
    
    ax2.set_title('Capital Preservation: Underwater Drawdown Profile', fontsize=16, fontweight='bold', pad=10)
    ax2.set_ylabel('Drawdown (%)', fontsize=12)
    ax2.set_xlabel('Date', fontsize=12)
    ax2.legend(loc='lower right', frameon=True)
    ax2.grid(True, linestyle='--', alpha=0.4)
    
    # Format Y-axis as percentage
    vals = ax2.get_yticks()
    ax2.set_yticklabels(['{:,.0%}'.format(x) for x in vals])
    
    plt.tight_layout()
    out_path = os.path.join(os.getcwd(), 'outputs', 'advanced_performance.png')
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    logging.info(f"Advanced institutional tear sheet saved safely to: {out_path}")

def main():
    logging.info("Starting Module 11: Deep Performance Analysis")
    df = load_trace()
    if df is None: return
    
    df = calculate_deep_metrics(df)
    analyze_periods(df)
    plot_advanced_metrics(df)

if __name__ == "__main__":
    main()
